### ISSUE TITLE
Добавить поддержку HQ в яндекс.музыку

### ISSUE THREAD

**Issue by asm0dey** [dandygithub/kodi#35]
Добавьте пожалуйста поддержку HQ для яндекс.плюсовиков

**Comment by DesSolo** [comment]
На момент написания плагина HQ была доступна только авторизванным пользователям по подписке.
На данный момент, у меня нет точных данных изменилась ли систуация.
Обратите внимание на последние страницы форума http://xbmc.ru/forum/showthread.php?t=20047 там Evld дорабатывает плагин. Правда не через этот репозиторий (придется скачивать zip с облака и обновлять руками)

**Comment by asm0dey** [comment]
Ну я вполне готов авторизоваться, более того, плагин сейчас этого требует :)
