### ISSUE TITLE
Не все ссылки работают на kinokong

### ISSUE THREAD

**Issue by IgorDan** [dandygithub/kodi#50]
Часть ссылок на контент не открываются. Во фрейме видео присутвуют и рабочие и не рабочие ссылки (разные проигрыватели). script.module.videohosts работает только с одними. Сайт конечно сделан странно, на одних страницах один набор прогрывателей, на других другой. Дорабатывать конечно геморойно :)).

**Comment by dandygithub** [comment]
Работают те, которые возможно дешифровать.
