### ISSUE TITLE
Update for Nexus version?

### ISSUE THREAD

**Issue by DownToTwo** [dandygithub/kodi#89]

**Comment by bxkr** [comment]
Stuck with 2.0.0 (from master's readme) not working on Nexus, but 2.1.0 from matrix branch worked https://github.com/dandygithub/kodi/blob/matrix/addons/zip/repository.dandy.kodi/repository.dandy.kodi-2.1.0.zip?raw=true

**Comment by dob777** [comment]
> Stuck with 2.0.0 (from master's readme) not working on Nexus, but 2.1.0 from matrix branch worked https://github.com/dandygithub/kodi/blob/matrix/addons/zip/repository.dandy.kodi/repository.dandy.kodi-2.1.0.zip?raw=true

thanks 2.1.0 worked for me too in Kodi 20.1

**Comment by dandygithub** [comment]
fix
